project:
  type: website
  output-dir: docs

website:
  title: "Vivian's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Pan Cancer Analysis"
        href: project_1/cBioPortal.qmd
      - text: "Neuroimaging Analysis"
        href: project_2/Dementia.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

