project:
  type: website
  output-dir: docs

website:
  title: "Vivian's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project_1/Dementia.qmd
      - project_2/cBioPortal.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

